<!-- HTML Document -->
<bbn-table :source="source.data"
           :pageable="true"
           :filterable="true"
           :sortable="true">
  <bbns-column field="child"
               :label="_('Process')"/>
  <bbns-column field="parent"
               :label="_('Parent')"/>
  <bbns-column field="ct"
               :width="100"
               type="number"
               :label="'#' + _('Calls')"/>
  <bbns-column field="wt"
               :width="100"
               type="number"
               :label="_('Wall time')"/>
  <bbns-column field="mem_aa"
               :width="120"
               type="number"
               :label="_('Total memory')"/>
  <bbns-column field="cpu"
               :width="100"
               type="number"
               :label="_('CPU')"/>
  <bbns-column field="mu"
               :width="100"
               type="number"
               :label="_('MU')"/>
  <bbns-column field="mem_na"
               :width="100"
               type="number"
               :label="_('Mem NA')"/>
  <bbns-column field="mem_nf"
               :width="100"
               type="number"
               :label="_('Mem NF')"/>
  <bbns-column field="pmu"
               :width="100"
               type="number"
               :label="_('PMU')"/>
</bbn-table>