<!-- HTML Document -->
<bbn-table :source="source.data"
           :pageable="true"
           :filterable="true"
           :sortable="true">
  <bbns-column field="child"
               :title="_('Process')"/>
  <bbns-column field="parent"
               :title="_('Parent')"/>
  <bbns-column field="ct"
               :width="100"
               type="number"
               :ftitle="_('The number of calls between parent and child')"
               :title="'#' + _('Calls')"/>
  <bbns-column field="wt"
               :width="100"
               type="number"
               :title="_('Wall time')"
               :ftitle="_('The summary wall time of all calls')"/>
  <bbns-column field="mem_aa"
               :width="120"
               type="number"
               :ftitle="_('The amount of allocated memory')"
               :title="_('Total memory')"/>
  <bbns-column field="cpu"
               :width="100"
               type="number"
               :ftitle="_('The cpu cycle time of all calls')"
               :title="_('CPU')"/>
  <bbns-column field="mu"
               :width="100"
               type="number"
               :ftitle="_('The sum of increase in memory_get_usage')"
               :title="_('MU')"/>
  <bbns-column field="mem_na"
               :width="100"
               type="number"
               :ftitle="_('The sum of the number of all allocations in this function')"
               :title="_('Mem NA')"/>
  <bbns-column field="mem_nf"
               :width="100"
               type="number"
               :ftitle="_('The sum of the number of all frees in this function')"
               :title="_('Mem NF')"/>
  <bbns-column field="pmu"
               :width="100"
               type="number"
               :ftitle="_('The sum of increase in memory_get_peak_usage')"
               :title="_('PMU')"/>
</bbn-table>